### PR TITLE
Fix path to calculate_ims

### PR DESCRIPTION
**Pull request by jpa198**
#### Checklist
- Have you updated the README (yes/no)?
- Have you updated the CHANGELOG (yes/no)?

### CODE REVIEW

**Review by shot0829 — APPROVED** [review]

**Review by jasonmotha — APPROVED** [review]
I'm confused as to how this issue came about. The directory/path hasn't changed for a long time?

**Comment by jpa198** [comment]
> I'm confused as to how this issue came about. The directory/path hasn't changed for a long time?

Looking back through the changes I have no idea how it ever worked... Was calculate_ims.py ever a top level script, living next to setup.py?

**Comment by jasonmotha** [comment]
image
The scripts part of the setup.py is the magic that you're missing.

**Review by sungeunbae — APPROVED** [review]

**Comment by jpa198** [comment]
> The scripts part of the setup.py is the magic that you're missing.
> 
> I believe when you install a package with scripts it allows them to be run ?globally?

Yeah, it was giving an absolute path though, so shouldn't have been able to pull the script out of the aether

**Pull request merged**
