### PR TITLE
Update auto_submit.py

### PR DESCRIPTION
**Pull request by mrldupuis**
resolves error messages

#### Checklist
- Have you updated the README (yes/no)?
- Have you updated the CHANGELOG (yes/no)?

### CODE REVIEW

**Review by sungeunbae — DISMISSED** [review]

**Review by sungeunbae — APPROVED** [review]

**Comment by sungeunbae** [comment]
@claudio525 will you approve this asap?

**Review by joelridden — APPROVED** [review]
The logic of this does not make sense to me, the only way the previous result could be an error is if the sim directory did not exist which seems unlikely to ever be the case as it would need to make both the sim dir and the ch_log dir. The exist ok being True is odd too me too because it would only get into that if statement if it doesn't exist.

But that being said it won't break anything having this merged, so sure.

**Review by claudio525 — APPROVED** [review]

**Comment by sungeunbae** [comment]
> The logic of this does not make sense to me, the only way the previous result could be an error is if the sim directory did not exist which seems unlikely to ever be the case as it would need to make both the sim dir and the ch_log dir. The exist ok being True is odd too me too because it would only get into that if statement if it doesn't exist.
> 
> But that being said it won't break anything having this merged, so sure.

Thanks - I think there was a corner case but can’t remember top of my head…

**Comment by sungeunbae** [comment]
> The logic of this does not make sense to me, the only way the previous result could be an error is if the sim directory did not exist which seems unlikely to ever be the case as it would need to make both the sim dir and the ch_log dir. The exist ok being True is odd too me too because it would only get into that if statement if it doesn't exist.
> 
> But that being said it won't break anything having this merged, so sure.

Oh, I was reading this on phone and thought this is something funky I experienced previously and left a comment advocating this change, but I get the different view reading in on a big screen. I find it odd too. I thought this was to handle exceptions such as the presence of a symbolic link or a file of the same name, but it doesn't seem to be a case. I think if os.path.isdir() can go.

**Pull request merged**
