### PR TITLE
Fix for Nurion im_plot and plot_ts 

### PR DESCRIPTION
**Pull request by sungeunbae**
#### Description
Plot_ts and IM_Plot on Nurion have been non-working. Specifically, 
1. IM_plot was never ported for PBS
2. Plot_ts had an error every time it executes `add_to_mgmt_queue.py` not being able to import workflow `from workflow.automation.lib.shared_automated_workflow import add_to_queue`.

Current status:
1. im_plot works on Nurion. This fix was not tested on NeSI.
2. plot_ts used to have the following issue, which appears to have gone away.

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/apps/applications/PYTHON/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/apps/applications/PYTHON/3.7/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home01/x2319a02/gmsim/Environments/v211213//visualization/animation/plot_ts.py", line 329, in render_slice
    contours=cpt_inc,
  File "/home01/x2319a02/gmsim/Environments/v211213/qcore/qcore/gmt.py", line 3667, in overlay
    copyfile(xyv_file, temp_grd)
  File "/apps/applications/PYTHON/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/pbs.9889020.pbs/tmpznkmh6ab/ts0261/ts.grd'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home01/x2319a02/gmsim/Environments/v211213//visualization/animation/plot_ts.py", line 365, in <module>
    pool.map(render_slice, range(xyts.t0, xyts.nt - xyts.t0))
  File "/apps/applications/PYTHON/3.7/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/apps/applications/PYTHON/3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/pbs.9889020.pbs/tmpznkmh6ab/ts0261/ts.grd'

```

Pending a test on NeSI.

### CODE REVIEW

**Comment by sungeunbae** [comment]
Will you have a look at this change? @jasonmotha @jpa198 ?
I am having a bit of issue with NeSI OTP and can't quite test this on NeSI. At least, this has been tested many times on Nurion and it is going strong.

**Review by jpa198 — COMMENTED** [review]
Looks good, am happy for it to go in once the nesi test is done

**Review by jasonmotha — APPROVED** [review]

**Review by jpa198 — APPROVED** [review]

**Comment by sungeunbae** [comment]
@jpa198 @jasonmotha  Tested on NeSI and sorted out  some issues found:
>> workflow/calculation/bb_sim.py:from workflow.calculation.site_response_BB import site_response
This needs `__init__.py` for import to work. 
Some old vm_params.yaml don't have MODEL_PARAMS at all, or sometimes MODEL_PARAMS are in full path - We assume it's in the same directory as the VM, so I think this fix is adequate, but I can already hear some outcry....

**Review by jpa198 — APPROVED** [review]

**Comment by jpa198** [comment]
> @jpa198 @jasonmotha Tested on NeSI and sorted out some issues found:
> 
> > > workflow/calculation/bb_sim.py:from workflow.calculation.site_response_BB import site_response
> 
> This needs `__init__.py` for import to work. Some old vm_params.yaml don't have MODEL_PARAMS at all, or sometimes MODEL_PARAMS are in full path - We assume it's in the same directory as the VM, so I think this fix is adequate, but I can already hear some outcry....

If MODEL_PARAMS is an absolute path, then a join operation will ignore the VM directory and use the given path (leading /). So this change may break things for legacy vm_params (not that they worked before this)

**Comment by sungeunbae** [comment]
> If MODEL_PARAMS is an absolute path, then a join operation will ignore the VM directory and use the given path (leading /). So this change may break things for legacy vm_params (not that they worked before this)

> MODEL_PARAMS: /nesi/nobackup/nesi00213/RunFolder/EndToEndTest/tests/test/Data/VMs/Hossack/model_params_rt01-h0.400
> sim_struct.get_fault_VM_dir(root_folder, run_name) -> /nesi/nobackup/nesi00213/RunFolder/EndToEndTest/tests/test/Data/VMs/Hossack
> os.path.basename(params.MODEL_PARAMS) -> model_params_rt01-h0.400
> os.path.join(sim_struct.get_fault_VM_dir(root_folder, run_name), os.path.basename(params.MODEL_PARAMS)) 
> -> /nesi/nobackup/nesi00213/RunFolder/EndToEndTest/tests/test/Data/VMs/Hossack/model_params_rt01-h0.400
>

**Review by jasonmotha — APPROVED** [review]
I can't recall anytime that Modelparams was outside of the VM Dir so this should be all good to go through.

**Pull request merged**
