### PR TITLE
added quotes on 000 to force it to be string

### PR DESCRIPTION
**Pull request by shot0829**
#### Checklist
- Have you updated the README (yes/no)?
- Have you updated the CHANGELOG (yes/no)?

### CODE REVIEW

**Review by jpa198 — APPROVED** [review]

**Comment by jasonmotha** [comment]
What bug is this fixing?
Also, shouldn't it then be used for 090?

**Comment by shot0829** [comment]
for some reason the yaml.load is treating 000 as int, while still treats 090 as string.

**Comment by shot0829** [comment]
i can add quotes on the 090 as well, for safety measures.

**Review by jasonmotha — APPROVED** [review]
Oh yep. For the recent add component change.

**Review by jpa198 — APPROVED** [review]

**Pull request merged**
