### PR TITLE
Emp automated

### PR DESCRIPTION
**Pull request by sungeunbae**
#### Description
Empirical calculation has been added as a part of automated workflow
#### Dependencies
Qcore, Empirical_Engine, IM_calc (rrup calculation)
#### Checklist
- Have you updated the README ? No
- Have you updated the CHANGELOG ?  Yes

### CODE REVIEW

**Comment by jasonmotha** [comment]
@sungeunbae I've approved but it seems to be failing unit tests still.

**Comment by sungeunbae** [comment]
> @sungeunbae I've approved but it seems to be failing unit tests still.

Yay, fixed the auto test!

**Comment by jasonmotha** [comment]
Oh before I approved this one, I wanted to ask what sdrop_adjust was used for in the past?

**Comment by sungeunbae** [comment]
> Oh before I approved this one, I wanted to ask what sdrop_adjust was used for in the past?

I have decoupled hf6.0.3 related stuff from this PR. 

https://github.com/ucgmsim/slurm_gm_workflow/commit/143937c84e7a042f5ee5fb3695cdd31e0d10bc48

Old sdrop_adjust has been replaced/extended to --stress_param_adj for HF6.0.3.

**Pull request merged**
